# Numpy入门
## 创建数组
- 用array函数转换
- 用numpy.arange方法生成

In [5]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
import numpy as np
my_arr1 = np.arange(100000)
my_arr1

array([    0,     1,     2, ..., 99997, 99998, 99999])

### 查看数组维度、形状、类型
- ndim
- shape
- dtype

In [11]:
my_arr1.ndim

1

In [12]:
my_arr1.shape

(100000,)

In [13]:
my_arr1.dtype

dtype('int64')

### 其他函数创建数组
- zeros和ones分别可以创建指定长度或形状的全0或全1数组。
- empty可以创建一个没有任何具体值的数组。
- 要用这些方法创建多维数组，只需传入一个表示形状的元组即可：

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.empty((2, 3, 2))

![](img/creat_ndarray.webp)

## ndarray的数据类型

> 通常只需要知道你所处理的数据的大致类型是浮点数、复数、整数、布尔值、字符串，还是普通的Python对象即可。

- datype:查看数据类型、声明数据类型
- astype:转换数据类型

In [16]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('int32')

In [17]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

> 笔记：调用astype总会创建一个新的数组（一个数据的备份），即使新的dtype与旧的dtype相同。

## NumPy 数组的运算

- 加
- 减
- 乘
- 除
- 平方等等跟矩阵运算一样

- 比较运算会产生布尔值
- 不同大小的数组之间的运算叫做广播（broadcasting），会传递到每一个值。

## 基本的索引和切片

In [18]:
# 索引
arr = np.arange(10)
arr[5]

5

In [19]:
# 切片
arr[5:8]

array([5, 6, 7])

In [20]:
# 广播
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

> 如上所示，当你将一个标量值赋值给一个切片时（如arr[5:8]=12），该值会自动传播（也就说后面将会讲到的“广播”）到整个选区。跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上。\
不懂看这：https://pyda.apachecn.org/#/docs/4?id=%e5%9f%ba%e6%9c%ac%e7%9a%84%e7%b4%a2%e5%bc%95%e5%92%8c%e5%88%87%e7%89%87

In [21]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [22]:
# 切片[:]会给数组中的所有值赋值
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

> 注意：如果你想要得到的是ndarray切片的一份副本而非视图，就需要明确地进行复制操作，例如arr[5:8].copy()

### 高维度数组
**高维度数组切片时先行再列**\
能做的事情更多。在一个二维数组中，各索引位置上的元素不再是标量而是一维数组

In [25]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# 下面是一样的
arr2d[0][2]
arr2d[0, 2]

3

In [28]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr3d[1, 0]

array([7, 8, 9])

>注意，在上面所有这些选取数组子集的例子中，返回的数组都是视图。

## 切片索引
ndarray的切片语法跟 Python 列表这样的一维对象差不多

In [32]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [33]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [34]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

>注意，“只有冒号”表示选取整个轴，因此你可以像下面这样只对高维轴进行切片

In [ ]:
arr2d[:, :1]

In [39]:
arr2d[:2, 1:] = 0 # 对切片赋值会扩散到整个数组
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 布尔型索引
利用布尔运算符索引时，前后数组的行数必须相同，列数可以不同。**把name列理解成表头。**

In [40]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [ ]:
names

In [ ]:
data

>假设每个名字都对应data数组中的一行，而我们想要选出对应于名字"Bob"的所有行。跟算术运算一样，数组的比较运算（如==）也是向量化的。

In [ ]:
names == 'Bob'

In [ ]:
data[names == 'Bob']

In [ ]:
# 这个布尔型数组可用于数组索引
data[names == 'Bob', 2:]

In [ ]:
data[names == 'Bob', 3]

In [ ]:
# 选取这三个名字中的两个需要组合应用多个布尔条件，使用&（和）、|（或）之类的布尔算术运算符即可
mask = (names == 'Bob') | (names == 'Will')
mask

In [ ]:
# 更改数值
data[data < 0] = 0
data

## 花式索引

In [56]:
arr = np.empty((8, 4)) # 生成8行4列的空值

for i in range(8): 
    arr[i] = i # 遍历的每个结果赋值给相应的行上的值

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [53]:
arr[[4, 3, 0, 6]] # 注意看[[]]意思是选取了4306开头的行

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [58]:
arr[[4, 3]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.]])

In [57]:
arr[4, 3]

4.0